language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  - extra-android-support
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew
- "./gradlew dependencies || true"
script:
- "./gradlew build install"
deploy:
  provider: releases
  api_key:
    secure: "kcR/w8oqOtmSio6BQzn0wzS6xPaa8qphEnH2M2ZNNCtEAuiaESB3XX0GIVCdQSL3GQtkVgRryBDBT5yNx6fTjU/jbl+KuRsIkBpqfZgZbMf6MFbdfWAsh6MPtSggwvvrmN/dlhnxbVm4ZllZ2/ilnJtSQFpCP4ZOhL9ie/dSvUmSSxZg1Kj2EWLy3IR/Izj6B7hYImdWBK37D0HFj+0Xcdzd1K73UssGAJy/xdjI2UzCg9O/uVmtAsFD/XkArCQYNJKvXosbV2OjgnG0hKitHwKh8TnvjCktiljKTINjmNSbfgBpUjQVb8J0DMHFr70ts2OSUJrBiRUkwmlB8pz1+EC370fD+3eqS3y8vksUiBLgKTGqOUPaEVfap4Y84mtdH0Iko3RIb8PfahtY4ObCMXJyDSUpBDiedyDQZCwi4Ckugd1uE+KMHR5PO+qAFtWd/lNPifm3NavBjuOuRPSWPK9bwf+N3KRmTjinoAz5l5N0A4GXgYwli5yEXU1BtG24FBLYGMwkHaw+I4iPQkTotWuvuXRLTewhJdFM4CYJ/+B2TT6uou4B5SywuKy8k3aw1dJOfUX0i4nsOWI49kOpUsZh6euK2dgUabnfVTKFlH3bqirgeL7YGgJCGouX75/XiOyYf+XwPARRXf70VG+bNMuFkdd7KteYt0MkgONZiOI="
  file:
    - library/build/outputs/aar/library-release.aar
    - library/build/libs/library-javadoc.jar
    - library/build/libs/library-sources.jar
  skip_cleanup: true
  on:
    tags: true
    repo: iplanetcn/phenix-utils
notifications:
  webhooks:
    secure: "XpVhGo2hVHTyDz+VJmnR1ihgaksHnL2hropAz5JcPfWVhQc7ZZw9VzH48bRI7xc8m79B/U38URYj2+C/mJcKaGLNvWqqInLfnKz0zwjns//tt2IRpmrmeHPoZpt67W9akXBUPEIA96fYozoGeU6srs2tCyVylHPjePnK1qZZEwhtVDRKYHK+WgOhdUrwpbuqdRW/qC8HoZ+mqblpYGJVOpvMrwg4sIjDIGQtwhCDIxY9ei3rpYbaLZUTrUfHOiCUL36hXcGyjyupEnoi1KuoRoU1IM8+RL2X0u84taQugovWnW2FiEcA9prsosE3/GeD2xUck7wKtUpToU5cWnkJlCFcnAQ0I3pyKfdfniQAffxNimVDYHtfp92jg4U68jtCkOUI6Krte88DR/vakJuKdlo0KXovy0emDdZymMrg5fLmrGBoL1sB9yuTz0MADzcPJJPCu8GK+rVth0Aov+cpDMfwASoAkPF76NbLkWzxBWVu7EMHmYLAgDPmP84rZ8+pYkUZ5feZh5OLCeq1dqMt/RTgJywf0nNp8DvCHX31Zsqj0WeJeoah4YlYXuzoQk/EmE4f4uJ7OO5PwvYudOaENAmJH0wrx7pR6lC7cZEgw6AUnaPjA0N+4UE4EmCV1lYD0NIQvvxi/5uNt7vcDZFk3hkVW4gbhpmV9tF/X1Yzd+I="
    on_success: always
    on_failure: always

