language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - yes | sdkmanager "build-tools;28.0.3"
script:
- "./gradlew build install"
deploy:
  provider: releases
  api_key:
    secure: "kcR/w8oqOtmSio6BQzn0wzS6xPaa8qphEnH2M2ZNNCtEAuiaESB3XX0GIVCdQSL3GQtkVgRryBDBT5yNx6fTjU/jbl+KuRsIkBpqfZgZbMf6MFbdfWAsh6MPtSggwvvrmN/dlhnxbVm4ZllZ2/ilnJtSQFpCP4ZOhL9ie/dSvUmSSxZg1Kj2EWLy3IR/Izj6B7hYImdWBK37D0HFj+0Xcdzd1K73UssGAJy/xdjI2UzCg9O/uVmtAsFD/XkArCQYNJKvXosbV2OjgnG0hKitHwKh8TnvjCktiljKTINjmNSbfgBpUjQVb8J0DMHFr70ts2OSUJrBiRUkwmlB8pz1+EC370fD+3eqS3y8vksUiBLgKTGqOUPaEVfap4Y84mtdH0Iko3RIb8PfahtY4ObCMXJyDSUpBDiedyDQZCwi4Ckugd1uE+KMHR5PO+qAFtWd/lNPifm3NavBjuOuRPSWPK9bwf+N3KRmTjinoAz5l5N0A4GXgYwli5yEXU1BtG24FBLYGMwkHaw+I4iPQkTotWuvuXRLTewhJdFM4CYJ/+B2TT6uou4B5SywuKy8k3aw1dJOfUX0i4nsOWI49kOpUsZh6euK2dgUabnfVTKFlH3bqirgeL7YGgJCGouX75/XiOyYf+XwPARRXf70VG+bNMuFkdd7KteYt0MkgONZiOI="
  file:
    - library/build/outputs/aar/library-release.aar
    - library/build/libs/library-javadoc.jar
    - library/build/libs/library-sources.jar
  skip_cleanup: true
  on:
    tags: true
    repo: iplanetcn/phenix-utils
notifications:
  webhooks: https://oapi.dingtalk.com/robot/send?access_token=2e8b3f2f9a9883440a1ebc40822aece5178f45a1689e74371284d0d13071121e


